
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_demo:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

raw:
  +materialized: table
  +schema: raw
  +s3_data_dir: s3://ole-datalake-prod-raw-us-east-2/
  +s3_staging_dir: s3://ole-athena-results-prod-us-east-2/dbt/raw/
  +incremental_strategy: insert_overwrite
  +table_type: hive
  +format: parquet
  +write_compression: snappy

intermediate:
  +materialized: table
  +schema: int
  +s3_data_dir: s3://ole-datalake-prod-int-us-east-2/
  +s3_staging_dir: s3://ole-athena-results-prod-us-east-2/dbt/int/
  +incremental_strategy: insert_overwrite
  +table_type: hive
  +format: parquet
  +write_compression: snappy

marts:
  +materialized: table
  +schema: marts
  +s3_data_dir: s3://ole-datalake-prod-marts-us-east-2/
  +s3_staging_dir: s3://ole-athena-results-prod-us-east-2/dbt/marts/
  +incremental_strategy: insert_overwrite
  +table_type: hive
  +format: parquet
  +write_compression: snappy

sync:
  +materialized: table
  +schema: sync